baseURL = "https://keps.bryanl.dev/"
languageCode = "en-us"
title = "KEP Viewer"
theme = "kep"

pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "UA-140853487-1"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 100

  [[menu.main]]
    identifier = "tags"
    name = "SIGs"
    url = "/sigs/"
    weight = 110

  [[menu.main]]
    identifier = "keps"
    name = "KEPs"
    url = "/keps/"
    weight = 120
